#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("xEDF.Droid.Resource", IsApplication=true)]

namespace xEDF.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Refractored.Xam.Vibrate.Resource.String.ApplicationName = global::xEDF.Droid.Resource.String.ApplicationName;
			global::Refractored.Xam.Vibrate.Resource.String.Hello = global::xEDF.Droid.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int app_icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int app_icon_round = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int edf_theme = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_content_copy_white_24dp = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_link_white_24dp = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_public_white_24dp = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_repeat_white_24dp = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ic_settings_white_24dp = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ic_verified_user_white_24dp = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int Splash = 2130837513;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f07001c
			public const int btnAuthorizeRD = 2131165212;
			
			// aapt resource value: 0x7f070007
			public const int btnCopyAuthorizationCode = 2131165191;
			
			// aapt resource value: 0x7f070012
			public const int btnCopyOriginal = 2131165202;
			
			// aapt resource value: 0x7f070024
			public const int btnCopyUnblocked = 2131165220;
			
			// aapt resource value: 0x7f070011
			public const int btnOpenOriginal = 2131165201;
			
			// aapt resource value: 0x7f070023
			public const int btnOpenUnblocked = 2131165219;
			
			// aapt resource value: 0x7f070027
			public const int btnSearch = 2131165223;
			
			// aapt resource value: 0x7f070013
			public const int btnShareOriginal = 2131165203;
			
			// aapt resource value: 0x7f070025
			public const int btnShareUnblocked = 2131165221;
			
			// aapt resource value: 0x7f070016
			public const int btnUnblock = 2131165206;
			
			// aapt resource value: 0x7f07002c
			public const int btnUpdateDontAskAgain = 2131165228;
			
			// aapt resource value: 0x7f07002b
			public const int btnUpdateNotNow = 2131165227;
			
			// aapt resource value: 0x7f07002a
			public const int btnUpdateNow = 2131165226;
			
			// aapt resource value: 0x7f070004
			public const int button2 = 2131165188;
			
			// aapt resource value: 0x7f07000b
			public const int justAListView1 = 2131165195;
			
			// aapt resource value: 0x7f07000c
			public const int justAnExpandableListView1 = 2131165196;
			
			// aapt resource value: 0x7f070019
			public const int labelError = 2131165209;
			
			// aapt resource value: 0x7f070014
			public const int labelLinkSupported = 2131165204;
			
			// aapt resource value: 0x7f070015
			public const int labelLinkUnsupported = 2131165205;
			
			// aapt resource value: 0x7f070022
			public const int labelUnblockedFileInfo = 2131165218;
			
			// aapt resource value: 0x7f07000f
			public const int labelUrl = 2131165199;
			
			// aapt resource value: 0x7f07001f
			public const int layoutMultiLinks = 2131165215;
			
			// aapt resource value: 0x7f070010
			public const int linearLayout1 = 2131165200;
			
			// aapt resource value: 0x7f070028
			public const int listViewSearchSuggestions = 2131165224;
			
			// aapt resource value: 0x7f07000a
			public const int mainWebView = 2131165194;
			
			// aapt resource value: 0x7f07002d
			public const int menuItemSettings = 2131165229;
			
			// aapt resource value: 0x7f070002
			public const int progressBar1 = 2131165186;
			
			// aapt resource value: 0x7f07000d
			public const int scrollView1 = 2131165197;
			
			// aapt resource value: 0x7f070021
			public const int spinnerMultiLinks = 2131165217;
			
			// aapt resource value: 0x7f070000
			public const int textView1 = 2131165184;
			
			// aapt resource value: 0x7f070018
			public const int textView16 = 2131165208;
			
			// aapt resource value: 0x7f07001e
			public const int textView17 = 2131165214;
			
			// aapt resource value: 0x7f07001b
			public const int textView18 = 2131165211;
			
			// aapt resource value: 0x7f070020
			public const int textView19 = 2131165216;
			
			// aapt resource value: 0x7f07000e
			public const int textView2 = 2131165198;
			
			// aapt resource value: 0x7f070003
			public const int textView3 = 2131165187;
			
			// aapt resource value: 0x7f070008
			public const int textView4 = 2131165192;
			
			// aapt resource value: 0x7f070006
			public const int tvAuthorizationCode = 2131165190;
			
			// aapt resource value: 0x7f070026
			public const int txtSearch = 2131165222;
			
			// aapt resource value: 0x7f070029
			public const int txtUpdateMessage = 2131165225;
			
			// aapt resource value: 0x7f070005
			public const int viewAuthorizationCode = 2131165189;
			
			// aapt resource value: 0x7f070017
			public const int viewErrorMessage = 2131165207;
			
			// aapt resource value: 0x7f070001
			public const int viewLoadingCode = 2131165185;
			
			// aapt resource value: 0x7f07001a
			public const int viewNotLoggedIn = 2131165210;
			
			// aapt resource value: 0x7f07001d
			public const int viewUnblockedLink = 2131165213;
			
			// aapt resource value: 0x7f070009
			public const int wvAuthorizationPage = 2131165193;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AuthorizeRD = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int HtmlContent = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int JustAListView = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int JustAnExpandableListView = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int LinkManager = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int SearchEngine = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int UpdatePopup = 2130903046;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f060000
			public const int SearchEngineMenu = 2131099648;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Theme_Splash = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
